on: 
  push:
  workflow_dispatch:

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    name: Trivy scan
    steps:
      - uses: actions/checkout@v4
      - uses: knqyf263/trivy-action@1a12292eac50a1a4bec4e98f32c43564e51cff1f
        with:
          scan-type: 'image'
          image-ref: 'jenkins:2.60.3'
          trivy-config: trivy.yaml
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
