on: 
  push:
  workflow_dispatch:

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    name: Trivy scan
    steps:
      - uses: actions/checkout@v4
        #- uses: knqyf263/trivy-action@1a12292eac50a1a4bec4e98f32c43564e51cff1f
      - run: |
          pwd
          ls -l
          ls -l /github/workspace
          ls -l /github/workspace/.github/workflows
      - uses: aquasecurity/trivy-action@0.25.0
        with:
          scan-type: 'image'
          image-ref: 'jenkins:2.60.3'
          format: 'template'
          template: '@/github/workspace/.github/workflows/html.tpl'
